openapi: 3.0.3
info:
  title: Developer API
  version: 1.0.0
  description: Developer API
tags:
  - name: developer
    description: Developer operations
paths:
  /api/developers:
    get:
      tags:
        - developer
      summary: Get all developers
      operationId: getDevelopers
      responses:
        '200':
          description: A list of developers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developers'
              example:
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "dev 1"
                  email: "dev1@gmail.com"
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "dev 2"
                  email: "dev2@gmail.com"
  /api/developer/{id}:
    #    get:
    #      tags:
    #        - developer
    #      summary: Get a developer by id
    #      operationId: getDeveloperById
    #      parameters:
    #        - in: path
    #          name: id
    #          required: true
    #          schema:
    #            type: string
    #          example: "65f3acb946a8a82e961b3fb9"
    #      responses:
    #        '200':
    #          description: A developer
    #          content:
    #            application/json:
    #              schema:
    #                $ref: '#/components/schemas/Developer'
    #              example:
    #                _id: "65f3acb946a8a82e961b3fb9"
    #                name: "dev 1"
    #                email: "dev1@gmail.com"
    delete:
      tags:
        - developer
      summary: Delete a developer by id
      operationId: deleteDeveloperById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          example: "65f3acb946a8a82e961b3fb9"
      responses:
        '200':
          description: A developer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developer'
              example:
                _id: "65f3acb946a8a82e961b3fb9"
                name: "dev 1"
                email: "dev1@gmail.com"


components:
  schemas:
    Developer:
      type: object
      properties:
        _id:
          type: string
          description: The id of the developer
          example: "65f3acb946a8a82e961b3fb9"
        name:
          type: string
          description: The name of the developer
          example: "dev 1"
        email:
          type: string
          description: The email of the developer
          example: "dev1@gmail.com"
    Developers:
      type: array
      items:
        $ref: '#/components/schemas/Developer'