openapi: 3.0.3
info:
  title: Manager API
  version: 1.0.0
  description: Manager API
tags:
  - name: manager
    description: Manager operations
paths:
  /api/managers:
    get:
      tags:
        - manager
      summary: Get all managers
      operationId: getManagers
      responses:
        '200':
          description: A list of managers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Managers'
              example:
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "Hű Jenő"
                  email: "hujeno@gmail.com"
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "Gec Imre"
                  email: "gecimre@gmail.com"
  /api/manager/{managerId}:
    get:
      tags:
        - manager
      summary: Get a manager by id
      operationId: getManagerById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          example: "65f3acb946a8a82e961b3fb9"
      responses:
        '200':
          description: A manager
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Manager'
              example:
                _id: "65f3acb946a8a82e961b3fb9"
                name: "Hű Jenő"
                email: "hujeno@gmail.com"
    delete:
      tags:
        - manager
      summary: Delete a manager by id
      operationId: deleteManagerById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          example: "65f3acb946a8a82e961b3fb9"
      responses:
        '200':
          description: Manager deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Manager deleted"
  /api/manager/{managerId}/tasks:
    get:
      tags:
        - manager
        - task
      summary: Get all tasks of a manager
      operationId: getTasksOfManager
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          example: "65f3acb946a8a82e961b3fb9"
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                $ref: './task.yaml#/components/schemas/Tasks'
              example:
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "Task 1"
                  description: "Description 1"
                  project_id: "65f60f8a89f811c81cef5238"
                  user_id: "65f3acb946a8a82e961b3fb9"
                  deadline: "2021-12-31T23:59:59.999Z"
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "Task 2"
                  description: "Description 2"
                  project_id: "65f60f8a89f811c81cef5238"
                  user_id: "65f3acb946a8a82e961b3fb9"
                  deadline: "2021-12-31T23:59:59.999Z"
  /api/manager/{managerId}/deadlines:
    get:
      tags:
        - manager
        - task
      summary: Get all tasks of a manager by deadline(Expires in a week)
      operationId: getTasksOfManagerByDeadline
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          example: "65f3acb946a8a82e961b3fb9"
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                $ref: './task.yaml#/components/schemas/Tasks'
              example:
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "Task 1"
                  description: "Description 1"
                  project_id: "65f60f8a89f811c81cef5238"
                  user_id: "65f3acb946a8a82e961b3fb9"
                  deadline: "2021-12-31T23:59:59.999Z"
                - _id: "65f3acb946a8a82e961b3fb9"
                  name: "Task 2"
                  description: "Description 2"
                  project_id: "65f60f8a89f811c81cef5238"
                  user_id: "65f3acb946a8a82e961b3fb9"
                  deadline: "2021-12-31T23:59:59.999Z"

components:
  schemas:
    Manager:
      type: object
      properties:
        _id:
          type: string
          example: "65f3acb946a8a82e961b3fb9"
        name:
          type: string
          example: "Hű Jenő"
        email:
          type: string
          example: "hujeno@gmail.com"
    Managers:
      type: array
      items:
        $ref: '#/components/schemas/Manager'

#    post:
#      summary: Create a new manager
#      operationId: createManager
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#      responses:
#        '201':
#          description: Manager created
#          content:
#            application/json:
#              schema:
#                type: array